apiVersion: v1
kind: Service
metadata:
  name: database
  labels: 
    group: frontend
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: database
  ports:
    - port: 3000          # port exposed outside ClusterIP
      targetPort: 3000    # port exposed by Pod