apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapi
  labels:
    app: restapi
    group: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi    # indicates which Pods (with which labeles) need be handled by this Deployment
  template:
    metadata:         # indicates the metadata that will be added to each Pod
      labels:
        app: restapi
        group: frontend
    spec:
      containers:     # defines a running container inside the Pod
        - name: restapi
          image: "422505755735.dkr.ecr.sa-east-1.amazonaws.com/k8simage:restapi-latest"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080   # which port of the container is exposed to the Pod
          env:
            - name: DBENDPOINT
              value: http://database:3000
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"

