apiVersion: v1
kind: Service
metadata:
  name: restapi
  labels: 
    group: frontend
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: restapi
  ports:
    - port: 8080          # port exposed outside ClusterIP
      targetPort: 8080    # port exposed by Pod
      